name: Build frontend

on:
  push
jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: eslint .
      - uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v4.2.0
